# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-02-27 07:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CityDict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='町')),
                ('desc', models.CharField(max_length=200, verbose_name='詳細')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'verbose_name': '町',
                'verbose_name_plural': '町',
            },
        ),
        migrations.CreateModel(
            name='CourseOrg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='スクール')),
                ('desc', models.TextField(verbose_name='スクール説明')),
                ('click_nums', models.IntegerField(default=0, verbose_name='クリック数')),
                ('fav_nums', models.IntegerField(default=0, verbose_name='気に入り数')),
                ('image', models.ImageField(upload_to='org/%Y/%m', verbose_name='ロゴ')),
                ('address', models.CharField(max_length=150, verbose_name='住所')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.CityDict', verbose_name='所在地')),
            ],
            options={
                'verbose_name': 'スクール',
                'verbose_name_plural': 'スクール',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='講師ネーム')),
                ('work_years', models.ImageField(default=0, upload_to='', verbose_name='実務年数')),
                ('work_company', models.CharField(max_length=50, null=True, verbose_name='所属企業')),
                ('work_position', models.CharField(max_length=50, null=True, verbose_name='役職')),
                ('points', models.CharField(max_length=50, null=True, verbose_name='教育手法')),
                ('click_nums', models.IntegerField(default=0, verbose_name='クリック数')),
                ('fav_nums', models.IntegerField(default=0, verbose_name='気に入り数')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.CourseOrg', verbose_name='所属スクール')),
            ],
            options={
                'verbose_name': '講師',
                'verbose_name_plural': '講師',
            },
        ),
    ]
