# Generated by Django 2.0 on 2019-03-05 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_auto_20190304_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseorg',
            name='category',
            field=models.CharField(choices=[('school', 'スクール'), ('individual', '個人'), ('university', '大学')], default='school', max_length=20, verbose_name='スクール分類'),
        ),
    ]
