# Generated by Django 2.0 on 2019-03-13 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_teacher_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='age',
            field=models.IntegerField(default=20, verbose_name='年齢'),
        ),
    ]
