# Generated by Django 2.0 on 2019-03-04 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursecomments',
            options={'verbose_name': 'コースレビュー', 'verbose_name_plural': 'コースレビュー'},
        ),
        migrations.AlterModelOptions(
            name='userask',
            options={'verbose_name': '問い合わせ', 'verbose_name_plural': '問い合わせ'},
        ),
        migrations.AlterModelOptions(
            name='usermessage',
            options={'verbose_name': 'メッセージ', 'verbose_name_plural': 'メッセージ'},
        ),
    ]
