# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-02-27 07:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='コースネーム')),
                ('desc', models.CharField(max_length=225, verbose_name='コース紹介')),
                ('detail', models.TextField(verbose_name='コース詳細')),
                ('degree', models.CharField(choices=[('easy', '入門'), ('usual', '中級'), ('difficult', '上級')], max_length=20)),
                ('learn_time', models.IntegerField(default=0, verbose_name='学習時間(分)')),
                ('students', models.IntegerField(default=0, verbose_name='学習人数')),
                ('fav_nums', models.IntegerField(default=0, verbose_name='お気に入り登録人数')),
                ('image', models.ImageField(upload_to='courses/%Y/%m', verbose_name='表紙')),
                ('click_nums', models.IntegerField(default=0, verbose_name='クリック数')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='挿入時間')),
            ],
            options={
                'verbose_name': 'コース',
                'verbose_name_plural': 'コース',
            },
        ),
        migrations.CreateModel(
            name='CourseResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='資料ネーム')),
                ('download', models.FileField(upload_to='course/resource/%Y/%m', verbose_name='資源ファイル')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='挿入時間')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course', verbose_name='コース')),
            ],
            options={
                'verbose_name': 'コース資源',
                'verbose_name_plural': 'コース資源',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='セッションネーム')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='挿入時間')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course', verbose_name='コース')),
            ],
            options={
                'verbose_name': 'セッション',
                'verbose_name_plural': 'セッション',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='動画ネーム')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='挿入時間')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Lesson', verbose_name='セッション')),
            ],
            options={
                'verbose_name': '動画',
                'verbose_name_plural': '動画',
            },
        ),
    ]
