# Generated by Django 2.0 on 2019-03-04 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='degree',
            field=models.CharField(choices=[('easy', '入門'), ('usual', '中級'), ('difficult', '上級')], max_length=20, verbose_name='難易度'),
        ),
    ]
