# Generated by Django 2.0 on 2019-03-08 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_course_org'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(default='ウェブ開発', max_length=20, verbose_name='コース区分'),
        ),
    ]
