# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-02-27 07:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='タイトル')),
                ('image', models.ImageField(upload_to='banner/%Y/%m', verbose_name='スライド')),
                ('url', models.URLField(verbose_name='url')),
                ('index', models.IntegerField(default=100, verbose_name='順番')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='挿入時間')),
            ],
            options={
                'verbose_name': 'スライド',
                'verbose_name_plural': 'スライド',
            },
        ),
        migrations.CreateModel(
            name='EmailVerifyRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='検証コード')),
                ('email', models.EmailField(max_length=50, verbose_name='メールアドレス')),
                ('send_type', models.CharField(choices=[('register', '新規ユーザー'), ('forget', 'パスワード再発行')], max_length=15)),
                ('send_time', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'verbose_name': 'メールアドレス検証コード',
                'verbose_name_plural': 'メールアドレス検証コード',
            },
        ),
    ]
